### ISSUE TITLE
I'd like to adopt the German translation!

### ISSUE THREAD

**Issue by arigawalin** [CalsiBotDev/CalsiBot#13]
### Commitment Statement
**I can confirm that I:**
- [x] Speak fluent German at a higher level than a regular native speaker, and can translate concepts and ideas to English confidently.
- [x] Will be able to promptly (on average, within 7 days) be able to review and correct new translations, or Pull Requests others have made with fixes.

### CalsiBot lists those who help translate a language when users select it.
**I want to be credited with a link to:**
- My GitHub profile

### Previous Contributions
**If you have made previous contributions to translations either for CalsiBot or some other project, please link to some examples of your work below:**
https://github.com/arigawalin/CalsiBot

**Comment by LucentW** [comment]
Hi @arigawalin,
as soon as you complete the translation, make sure to do a pull request here, so that @CalsiBotDev can check that out and merge it.

Also, feel free to join https://t.me/cringe if you need to talk to Calsï directly

**Comment by arigawalin** [comment]
@LucentW Alright. Will do. I'll work on it in the following days when I can.

**Comment by CalsiBotDev** [comment]
Thanks @arigawalin!

I look forward to seeing your translations once they are ready.

**Comment by CalsiBotDev** [comment]
https://github.com/CalsiBotDev/CalsiBot/pull/16
