### ISSUE TITLE
correction for german file

### ISSUE THREAD

**Issue by Heinz14** [CalsiBotDev/CalsiBot#31]
`"generic.cantUseFeatureOnAdmins": "<b>Du kannst Adminsnicht nicht </b><code>%s</code><b> ... Leider</b>"`
The "nicht" behind "Admins" and "... Leider" is too much. It should be: 
`"<b>Du kannst Admins nicht </b><code>%s</code>"`

**Comment by CalsiBotDev** [comment]
Thank you, the first part will be fixed very soon. The German translator suggests to keep `... Leider`.
